# Generated by Django 5.0.1 on 2024-01-10 14:12

from django.db import migrations, models

import weather.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now=True, verbose_name="Datetime"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Forecast data")),
                (
                    "detailing_type",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("minutely", "Minutely"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        max_length=10,
                        verbose_name="Detailing type",
                    ),
                ),
                (
                    "lat",
                    weather.fields.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "lon",
                    weather.fields.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
            ],
        ),
    ]
